CREATE DATABASE book_manage;
USE book_manage;

CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR(32) NOT NULL,
	MEMBER_PW VARCHAR(64) NOT NULL,
	MEMBER_NAME VARCHAR(32) NOT NULL,
	MEMBER_NAME_KANA VARCHAR(32) NOT NULL,
	MEMBER_TEL VARCHAR(16) NOT NULL,
	MEMBER_MAIL VARCHAR(128) NOT NULL,
	MEMBER_ZIPCODE VARCHAR(16) NOT NULL,
	MEMBER_ADD_1 VARCHAR(128) NOT NULL,
	MEMBER_ADD_2 VARCHAR(128) NOT NULL,
	MEMBER_ADD_3 VARCHAR(128) NOT NULL,
	MEMBER_TYPE INT NOT NULL,
	DELETE_FLAG TINYINT NOT NULL,
	CREATE_USER BIGINT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	UPDATE_USER BIGINT NOT NULL,
	UPDATE_DATE DATETIME NOT NULL,
	PRIMARY KEY(MEMBER_ID)
);

CREATE TABLE BOOK(
	BOOK_NO INT NOT NULL,
	BOOK_CATEGORY VARCHAR(32) NOT NULL,
	BOOK_NAME VARCHAR(32) NOT NULL,
	BOOK_WRITER VARCHAR(32) NOT NULL,
	BOOK_PUBLISHER VARCHAR(32) NOT NULL,
	BOOK_PUBLISHING_DATE DATETIME,
	BOOK_CONTENT VARCHAR(128),
	BOOK_PRICE FLOAT NOT NULL,
	BOOK_IMAGE VARCHAR(128) NOT NULL,
	BOOK_ISBN VARCHAR(16) NOT NULL,
	DELETE_FLAG TINYINT NOT NULL,
	CREATE_USER BIGINT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	UPDATE_USER BIGINT NOT NULL,
	UPDATE_DATE DATETIME NOT NULL,
	PRIMARY KEY(BOOK_NO)
);

CREATE TABLE CART(
	CART_NO INT NOT NULL,
	CART_MEMBER_ID VARCHAR(32) NOT NULL,
	CART_BOOK_NO INT NOT NULL,
	CART_COUNT TINYINT NOT NULL,
	CART_GENERATE_DATE DATETIME NOT NULL,
	DELETE_FLAG TINYINT NOT NULL,
	CREATE_USER BIGINT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	UPDATE_USER BIGINT NOT NULL,
	UPDATE_DATE DATETIME NOT NULL,
	PRIMARY KEY(CART_NO)
);

CREATE TABLE BOOK_ORDER(
	ORDER_NO INT NOT NULL,
	ORDER_ITEM_NO INT NOT NULL,
	ORDER_BOOK_NO INT NOT NULL,
	ORDER_STATUS TINYINT NOT NULL,
	ORDER_COUNT TINYINT NOT NULL,
	ORDER_MEMBER_ID VARCHAR(32) NOT NULL,
	ORDER_MEMO VARCHAR(128),
	ORDER_TRADE_TYPE VARCHAR(32) NOT NULL,
	ORDER_TRADE_DATE DATETIME NOT NULL,
	ORDER_DATE DATETIME NOT NULL,
	ORDER_RECEIVE_NAME VARCHAR(32) NOT NULL,
	ORDER_RECEIVE_NAME_KANA VARCHAR(32) NOT NULL,
	ORDER_RECEIVE_EMAIL VARCHAR(128) NOT NULL,
	ORDER_RECEIVE_TEL VARCHAR(16) NOT NULL,
	ORDER_RECEIVE_ZIPCODE VARCHAR(16) NOT NULL,
	ORDER_RECEIVE_ADD_1 VARCHAR(128) NOT NULL,
	ORDER_RECEIVE_ADD_2 VARCHAR(128) NOT NULL,
	ORDER_RECEIVE_ADD_3 VARCHAR(128) NOT NULL,
	DELETE_FLAG TINYINT NOT NULL,
	CREATE_USER BIGINT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	UPDATE_USER BIGINT NOT NULL,
	UPDATE_DATE DATETIME NOT NULL,
	PRIMARY KEY(ORDER_NO, ORDER_ITEM_NO)
);

CREATE TABLE ZIPCODE (
	ZIPCODE VARCHAR(16) NOT NULL,
	ADD_1 VARCHAR(128) NOT NULL,
	ADD_2 VARCHAR(128) NOT NULL,
	ADD_3 VARCHAR(128) NOT NULL,
	DELETE_FLAG TINYINT NOT NULL,
	CREATE_USER BIGINT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	UPDATE_USER BIGINT NOT NULL,
	UPDATE_DATE DATETIME NOT NULL
);
