CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR(20),
	MEMBER_PW VARCHAR(15),
	MEMBER_NAME VARCHAR(20),
	MEMBER_JUMIN1 INT,
	MEMBER_JUMIN2 INT,
	MEMBER_EMAIL VARCHAR(25),
	MEMBER_EMAIL_GET VARCHAR(7),
	MEMBER_MOBILE VARCHAR(13),
	MEMBER_PHONE VARCHAR(13),
	MEMBER_ZIPCODE VARCHAR(13),
	MEMBER_ADDR1 VARCHAR(70),
	MEMBER_ADDR2 VARCHAR(70),
	MEMBER_ADMIN INT,
	MEMBER_JOIN_DATE DATE
);

CREATE TABLE ZIPCODE(
	ID INT,
	ZIPCODE VARCHAR(7),
	SIDO VARCHAR(10),
	GUGUN VARCHAR(30),
	DONG VARCHAR(36),
	RI VARCHAR(60),
	BUNJI VARCHAR(50),
	PRIMARY KEY (ID)
);

CREATE TABLE BOOK(
	BOOK_NUM INT,
	BOOK_CATEGORY VARCHAR(20),
	BOOK_NAME VARCHAR(50),
	BOOK_CONTENT VARCHAR(3000),
	BOOK_SIZE VARCHAR(10),
	BOOK_COLOR VARCHAR(20),
	BOOK_AMOUNT INT,
	BOOK_PRICE INT,
	BOOK_IMAGE VARCHAR(100),
	BOOK_BEST INT,
	BOOK_DATE DATE,
	PRIMARY KEY(BOOK_NUM)
);

CREATE TABLE CART(
	CART_NUM INT,
	CART_MEMBER_ID VARCHAR(20),
	CART_BOOK_NUM INT,
	CART_BOOK_AMOUNT INT,
	CART_BOOK_SIZE VARCHAR(20),
	CART_BOOK_COLOR VARCHAR(20),
	CART_DATE DATE,
	PRIMARY KEY(CART_NUM)
);

CREATE TABLE BOOK_ORDER(
	ORDER_NUM INT,
	ORDER_TRADE_NUM VARCHAR(50),
	ORDER_TRANS_NUM VARCHAR(50),
	ORDER_BOOK_NUM INT,
	ORDER_BOOK_NAME VARCHAR(50),
	ORDER_BOOK_AMOUNT INT,
	ORDER_BOOK_SIZE VARCHAR(20),
	ORDER_BOOK_COLOR VARCHAR(20),
	ORDER_MEMBER_ID VARCHAR(20),
	ORDER_RECEIVE_NAME VARCHAR(20),
	ORDER_RECEIVE_ADDR1 VARCHAR(70),
	ORDER_RECEIVE_ADDR2 VARCHAR(70),
	ORDER_RECEIVE_PHONE VARCHAR(13),
	ORDER_RECEIVE_MOBILE VARCHAR(13),
	ORDER_MEMO VARCHAR(3000),
	ORDER_SUM_MONEY INT,
	ORDER_TRADE_TYPE VARCHAR(20),
	ORDER_TRADE_DATE DATE,
	ORDER_TRADE_PAYER VARCHAR(20),
	ORDER_DATE DATE,
	ORDER_STATUS INT,
	PRIMARY KEY(ORDER_NUM)
);





--以下、ドンゴン作成分

CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR(32),
	MEMBER_PW VARCHAR(64),
	MEMBER_NAME VARCHAR(32),
	MEMBER_NAME_KANA VARCHAR(32),
	MEMBER_EMAIL VARCHAR(128),
	MEMBER_PHONE VARCHAR(16),
	ZIPCODE VARCHAR(16),
	ADD_1 VARCHAR(128),
	ADD_2 VARCHAR(128),
	ADD_3 VARCHAR(128),
	DELETE_FLAG TINYINT,
	CREATE_USER BIGINT,
	CREATE_DATE DATETIME,
	UPDATE_USER BIGINT,
	UPDATE_DATE DATETIME,
	PRIMARY KEY(MEMBER_ID)
);

CREATE TABLE ZIPCODE (
	ZIPCODE VARCHAR(16),
	ADD_1 VARCHAR(128),
	ADD_2 VARCHAR(128),
	ADD_3 VARCHAR(128),
	DELETE_FLAG TINYINT,
	CREATE_USER BIGINT,
	CREATE_DATE DATETIME,
	UPDATE_USER BIGINT,
	UPDATE_DATE DATETIME
);

CREATE TABLE BOOK(
	BOOK_NO INT,
	BOOK_CATEGORY VARCHAR(32),
	BOOK_NAME VARCHAR(32),
	BOOK_WRITER VARCHAR(32),
	BOOK_PUBLISHER VARCHAR(32),
	BOOK_PUBLISHING_DATE DATETIME,
	BOOK_CONTENT VARCHAR(128),
	BOOK_PRICE FLOAT,
	BOOK_IMAGE VARCHAR(64),
	BOOK_ISBN VARCHAR(16),
	DELETE_FLAG TINYINT,
	CREATE_USER BIGINT,
	CREATE_DATE DATETIME,
	UPDATE_USER BIGINT,
	UPDATE_DATE DATETIME,
	PRIMARY KEY(BOOK_NO)
);

CREATE TABLE CART(
	CART_NO INT,
	CART_MEMBER_ID VARCHAR(32),
	CART_BOOK_NO INT,
	CART_COUNT TINYINT,
	CART_DATE DATETIME,
	DELETE_FLAG TINYINT,
	CREATE_USER BIGINT,
	CREATE_DATE DATETIME,
	UPDATE_USER BIGINT,
	UPDATE_DATE DATETIME,
	PRIMARY KEY(CART_NO)
);

CREATE TABLE BOOK_ORDER(
	ORDER_NO INT,
	ORDER_TRANS_NO VARCHAR(32),
	ORDER_BOOK_NO INT,
	ORDER_BOOK_NAME VARCHAR(32),
	ORDER_BOOK_PRICE FLOAT,
	ORDER_COUNT TINYINT,
	ORDER_TOTAL_PRICE TINYINT,
	ORDER_MEMBER_ID VARCHAR(32),
	ORDER_RECEIVE_NAME VARCHAR(32),
	ORDER_RECEIVE_NAME_KANA VARCHAR(32),
	ORDER_RECEIVE_ADDR1 VARCHAR(128),
	ORDER_RECEIVE_ADDR2 VARCHAR(128),
	ORDER_RECEIVE_ADDR3 VARCHAR(128),
	ORDER_MEMBER_PHONE VARCHAR(16),
	ORDER_MEMO VARCHAR(128),
	ORDER_TRADE_TYPE VARCHAR(32),
	ORDER_TRADE_DATE DATETIME,
	ORDER_TRADE_PAYER VARCHAR(32),
	ORDER_DATE DATETIME,
	ORDER_STATUS TINYINT,
	PRIMARY KEY(ORDER_NO)
);
