DROP TABLE MEMBER;
CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR2(20),
	MEMBER_PW VARCHAR2(15),
	MEMBER_NAME VARCHAR2(20),
	MEMBER_JUMIN1 NUMBER,
	MEMBER_JUMIN2 NUMBER,
	MEMBER_EMAIL VARCHAR2(25),
	MEMBER_EMAIL_GET VARCHAR2(7),
	MEMBER_MOBILE VARCHAR2(13),
	MEMBER_PHONE VARCHAR2(13),
	MEMBER_ZIPCODE VARCHAR2(13),
	MEMBER_ADDR1 VARCHAR2(70),
	MEMBER_ADDR2 VARCHAR2(70),
	MEMBER_ADMIN NUMBER,
	MEMBER_JOIN_DATE DATE
);

CREATE TABLE ZIPCODE (
  ID NUMBER,
  ZIPCODE VARCHAR2(7),
  SIDO VARCHAR2(10),
  GUGUN VARCHAR2(30),
  DONG VARCHAR2(36),
  RI VARCHAR2(60),
  BUNJI VARCHAR2(50),
  PRIMARY KEY (ID)
);

CREATE TABLE BOOK(
	BOOK_NUM NUMBER,
	BOOK_CATEGORY VARCHAR2(20),
	BOOK_NAME VARCHAR2(50),
	BOOK_CONTENT VARCHAR2(3000),
	BOOK_SIZE VARCHAR2(10),
	BOOK_COLOR VARCHAR2(20),
	BOOK_AMOUNT NUMBER,
	BOOK_PRICE NUMBER,
	BOOK_IMAGE VARCHAR2(50),
	BOOK_BEST NUMBER,
	BOOK_DATE DATE,
	PRIMARY KEY(BOOK_NUM)
);

CREATE TABLE CART(
	CART_NUM NUMBER,
	CART_MEMBER_ID VARCHAR2(20),
	CART_BOOK_NUM NUMBER,
	CART_BOOK_AMOUNT NUMBER,
	CART_BOOK_SIZE VARCHAR2(20),
	CART_BOOK_COLOR VARCHAR2(20),
	CART_DATE DATE,
	PRIMARY KEY(CART_NUM)
);

CREATE TABLE BOOK_ORDER(
	ORDER_NUM NUMBER,
	ORDER_TRADE_NUM VARCHAR2(50),
	ORDER_TRANS_NUM VARCHAR2(50),
	ORDER_BOOK_NUM	NUMBER,
	ORDER_BOOK_NAME VARCHAR2(50),
	ORDER_BOOK_AMOUNT NUMBER,
	ORDER_BOOK_SIZE VARCHAR2(20),
	ORDER_BOOK_COLOR VARCHAR2(20),
	ORDER_MEMBER_ID VARCHAR2(20),
	ORDER_RECEIVE_NAME VARCHAR2(20),
	ORDER_RECEIVE_ADDR1 VARCHAR2(70),
	ORDER_RECEIVE_ADDR2 VARCHAR2(70),
	ORDER_RECEIVE_PHONE VARCHAR2(13),
	ORDER_RECEIVE_MOBILE VARCHAR2(13),
	ORDER_MEMO VARCHAR2(3000),
	ORDER_SUM_MONEY NUMBER,
	ORDER_TRADE_TYPE VARCHAR2(20),
	ORDER_TRADE_DATE DATE,
	ORDER_TRADE_PAYER VARCHAR2(20),
	ORDER_DATE DATE,
	ORDER_STATUS NUMBER,
	PRIMARY KEY(ORDER_NUM)
);

DELETE cart;
COMMIT

SELECT * FROM cart;